version: 2.1
machine: true

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:14.0.2-jdk-buster'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud with CircleCI
          command: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud